### ISSUE TITLE
Update pypi repository to 0.5

### ISSUE THREAD

**Issue by jnslmk** [DanielSank/observed#19]
The version at pypi is 0.4 although 0.5 already exists.

**Comment by DanielSank** [comment]
Yep. PyPI's workflow changed and I never bothered to learn the new way. Guess it's about time ;-)

**Comment by DanielSank** [comment]
Actually no, 0.5 is not complete.

**Comment by rockobonaparte** [comment]
There's some stuff in 0.4 that was already fixed in the 0.5 master. I was about to file an issue to ask for the same thing. What in particular is incomplete for the 0.5 milestone?

**Comment by DanielSank** [comment]
@rockobonaparte https://github.com/DanielSank/observed/issues/7 is the last remaining issue for 0.5. The documentation is really repetitive and kind of hard to understand.

**Comment by DanielSank** [comment]
I'll try to get 0.5 onto PyPI but the end of the day today :-)

**Comment by DanielSank** [comment]
Made a bunch of progress today in the `cleanup` branch.

**Comment by DanielSank** [comment]
Updated pypi to version 0.5.1.

**Comment by rockobonaparte** [comment]
Is that a complete package? I couldn't import "observed" afterwards so I downloaded the wheel and poked around inside. All I got was the .dist-info folder.

**Comment by DanielSank** [comment]
@rockobonaparte you're right. I just bumped the version number uploaded 0.5.2 to `test.pypi` [here](https://test.pypi.org/project/observed/). I then pip installed it and can't import. There must be something wrong with `setup.py`. I'm debugging, but if you can figure it out I'll appreciate the help.

**Comment by DanielSank** [comment]
This may have something to do with the fact that observed is distributed as a single module but I put a `packages` line in `setup.py`.

**Comment by DanielSank** [comment]
Ok I think I fixed it. Please confirm.

**Comment by rockobonaparte** [comment]
I just pulled 0.5.3 and there's stuff now. I can't tell you any more than that because it blew up trying to import event. Well, in particular my Python 2.7 instance choked on the f-string in an exception trying to manage a failure to import event c/o get_observable_method. I'm guessing the whole paradigm has changed and that's my problem. My 3.6 environment's are sketchy right now so I couldn't tell you how well they're doing there.

**Comment by rockobonaparte** [comment]
I can sort out what is what later, but I just tried to scramble and kick it once for you for the sake of confirmation.

**Comment by DanielSank** [comment]
@rockobonaparte The interface had a slight change and `@event` no longer exists. Fortunately, a relatively simple find-replace can deal with the change. See the `README` and `NEWS` files.
